### ISSUE TITLE
I have the gpx data for RY

### ISSUE THREAD

**Issue by aaryno** [ebrensi/running_data#6]
Will try to get it to you Sunday.

**Comment by ebrensi** [comment]
haha ok!

**Comment by aaryno** [comment]
How do you want it? My dropbox is full :-\

**Comment by ebrensi** [comment]
How about a github repo with the files in it?

**Comment by aaryno** [comment]
https://github.com/aaryno/ry16_transcon_data

**Comment by ebrensi** [comment]
ok I'm working on it now.
